services:
  - type: web
    name: bulkwala-backend
    env: node
    plan: free
    buildCommand: pnpm install --frozen-lockfile
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000